name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./ArticuChic/package-lock.json"

      - name: Install Dependencies
        run: |
          cd ArticuChic
          npm ci --legacy-peer-deps

      - name: Build
        run: |
          cd ArticuChic
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ArticuChic/dist
          branch: gh-pages
          clean: true # Automatically remove deleted files from the deploy branch
